# Structure

This analysis using vegnasis package explores vegetation structure.

## Data Processing

```{r warning=FALSE, message = FALSE}
# remotes::install_github("phytoclast/vegnasis", dependencies = FALSE)
library(vegnasis)
library(ggplot2)

veg.raw <- vegnasis::nasis.veg
veg <- clean.veg(veg.raw)
#These tasks fill in missing plant 'types' and establishes the crown heights based on user inputs of stratum, live canopy heights, and taxon norms when user data is missing.
veg <- veg |> fill.type.df() |> fill.hts.df()
#Select only Wexford County Michigan records.
veg <-  veg |> subset(grepl('MI165',plot))
```

## Structure Summary

```{r warning=FALSE, message = FALSE}
veg.structure <- veg |> get.structure()

knitr::kable(
  veg.structure, booktabs = TRUE,
  caption = 'A table with estimating structure of each plot.'
)

```

## Structure Profile

```{r warning=FALSE, message = FALSE}
veg.str <- summary.crown.thickness(veg, breaks = c(c(-1:9)/10,c(2:100)/2)) |> structure.fill.zero() |> subset(type %in% c('tree', 'shrub/vine', 'grass/grasslike',  'forb'))
veg.str.pct <- veg.str |> group_by(type, stratum, stratum.label, bottom, top) |>
  summarise(X25 = quantile(Cover, 0.25),
            X50 = quantile(Cover, 0.5),
            X75 = quantile(Cover, 0.75))

knitr::kable(
  head(veg.str, 25), booktabs = TRUE,
  caption = 'A table of the first 25 rows of the veg.str data.'
)

```



```{r warning=FALSE, message = FALSE, fig.cap = "Structure of plot collection."}

ggplot(veg.str.pct, aes(x = top, y = X50, col=type)) +
  # plot median
  geom_line() +
  # plot quantiles
  geom_ribbon(aes(ymin = X25, ymax = X75, x = top, fill=type), alpha = 0.2) +
  coord_flip() +
  theme(legend.position = "none")+
  scale_x_continuous(name='height (m)', breaks=c(0:100)*5,  minor_breaks = NULL, limits = c(0,40))+
  scale_y_continuous(name='cover')+
  facet_wrap(~ type, scales = "free_x", nrow=1)

```

```{r warning=FALSE, message = FALSE, fig.cap = "Structure of plot collection, rescaled."}
#Custom transformation as a function passing a parameter to existing function. Default sigma of trans = 'pseudo_log' is 1, so in this case, calling the custom function with sigma = 1 is the same as calling trans = 'pseudo_log'. Call custom transformation as trans = 'ps2'. Ggplot appends '_trans' to the name of the function called, so our function needs to have this appended to its name.  But in this data set, trans='sqrt' is preferable as it doesn't overly compress the highest canopy.
ps2_trans <- function() {
  scales::pseudo_log_trans(sigma = 1)
}

ggplot(veg.str.pct, aes(x = top, y = X50, col=type)) +
  # plot median
  geom_line() +
  # plot quantiles
  geom_ribbon(aes(ymin = X25, ymax = X75, x = top, fill=type), alpha = 0.2) +
  coord_flip() +
  theme(legend.position = "none")+
  scale_x_continuous(name='height (m)', breaks=c(c(0:4),c(1:100)*5),  minor_breaks = NULL, limits = c(0,40), trans = 'sqrt')+
  scale_y_continuous(name='cover')+
  facet_wrap(~ type, scales = "free_x", nrow=1)

```
