# Summarizing DSP Projects

The following scripts demonstrate a possible workflow for summarizing the vegetation data from a Dynamic Soil Properties (DSP) project. 

### Tabular Summaries 


```{r warning=FALSE, message = FALSE, eval=TRUE}
#remotes::install_github("ncss-tech/soilDB", dependencies = FALSE) #install latest version of SoilDB package
#remotes::install_github("phytoclast/vegnasis", dependencies = FALSE) #install latest version of vegnasis package
library(soilDB)
library(vegnasis)

#Create conditional rounding functions
condRound10 <- function(x){
  x <- ifelse(x < 0.05, 0, ifelse(x < 10, round(x, 1), round(x,0)))
  x <- as.character(x)
  return(x)
}
condRound1 <- function(x){
  x <-  ifelse(x < 0.05, 0, ifelse(x < 1, round(x, 1), round(x,0)))
  x <- as.character(x)
  return(x)
}


#Load Demo Data 
siteass <- vegnasis::siteass20250414
sites <- vegnasis::sites20250414
veg.raw <- vegnasis::veg.raw20250414
vegplot <- vegnasis::vegplot20250414
vegground <- vegnasis::vegground20250414

#To use your own data, remove # below
# siteass <- get_site_association_from_NASIS(SS=F)
# sites <- get_site_data_from_NASIS_db(SS=F)
# veg.raw <- soilDB::get_vegplot_species_from_NASIS_db(SS=F)
# vegplot <- soilDB::get_vegplot_from_NASIS_db(SS=F)
# vegground <- get_vegplot_groundsurface_from_NASIS_db(SS=F)

    
#narrow to a project (user site association id)
thesesites <- subset(siteass, usiteassocid %in% 'DSP-F094AB019MI-2024')
sites <- subset(sites, usiteid %in% thesesites$usiteid)

landuse <- data.frame(siteobsiid=sites$siteobsiid, landuse = sites$commphasename)
landuse <- landuse |> left_join(data.frame(siteobsiid=vegplot$siteobsiid, plot = vegplot$vegplotid)) |> subset(!is.na(plot) & !is.na(landuse))
veg <- clean.veg(veg.raw)|> subset(!is.na(taxon)) 
veg <- veg |> inner_join(landuse)

veg <- veg |> mutate(type=NA) |> fill.type.df() |> fill.hts.df()
veg <- veg |> mutate(taxon = harmonize.taxa(veg$taxon, fix = TRUE, sensu = "usda"))

#Get vegetation Structure ----
veg.str <- veg |> get.structure(simple = TRUE)



veg.str <- veg.str |> inner_join(landuse)
veg.str.long <- tidyr::pivot_longer(veg.str, c(tree,shrub,herb,moss,ht.max))
veg.str.summary <- veg.str.long |> group_by(landuse, name) |> summarise(Low = round(quantile(value,0.05),1),
                                                                 RV = round(mean(value),1),
                                                                 High = round(quantile(value,0.95),1))

veg.str.wide <- tidyr::pivot_wider(veg.str.summary, names_from = landuse, values_from = c(Low,RV,High)) |> as.data.frame()

#kableextra ----
library(knitr)
library(kableExtra)


df2 <- veg.str.summary |> group_by(landuse) |> arrange()
df2$name <- factor(df2$name, levels = c('ht.max','tree','shrub','herb','moss'))
df2 <- df2[order(df2$landuse,df2$name),]
df2 |>
  knitr::kable(row.names = FALSE, digits = c(0,0,0,0)) |>
  remove_column(1) |>
  kableExtra::group_rows(index = table(df2$landuse)) |>
  # kableExtra::kable_paper("hover", full_width = F)
kable_classic(full_width = F, html_font = "Cambria")


#flextable ----
library(flextable)


pcolors <- palette.colors(length(unique(veg.str$landuse))+1, palette = "ggplot2")
pcolors <- pcolors[2:length(pcolors)]
pcolors <- c('white',pcolors,pcolors,pcolors)
thcols <- 1:length(unique(veg.str$landuse))
thcols <- 3*thcols+1
df2 <- veg.str.wide
df2$name <- factor(df2$name, levels = c('ht.max','tree','shrub','herb','moss'))
df2 <- df2[order(df2$name),]
df2$name <- c('Maximum Height (m)','Tree (%)','Shrub (%)','Herb (%)','Moss (%)')

repnames <- colnames(df2)
repnames <- stringr::str_split_fixed(repnames, '_', 2)
repnamesA <- repnames[,2]
repnamesB <- repnames[,1]
repdf <- data.frame(A=repnamesA, B=repnamesB, C=pcolors)
repdf <- repdf |> mutate(seq = 1:nrow(repdf))
repdf <- repdf |> arrange(A)
repnames <- paste0(repnames[,2],'_',repnames[,1])
colnames(df2) <- repnames 
df2 <- df2[,repdf$seq]
colnames(df2)[1]<-'Variable'

theme_design <- function(x) {
  x <- border_remove(x)
  std_border <- fp_border_default(width = 0.5, color = "black")
  thk_border <- fp_border_default(width = 2, color = "black")
  x <- fontsize(x, size = 10, part = "all")
  x <- font(x, fontname = "Cambria", part = "all")
  x <- align(x, align = "center", part = "all")
  x <- bold(x, bold = TRUE, part = "all")
  x <- bg(x, bg = "white", part = "body")
  x <- bg(x, bg = repdf$C, part = "header")
  x <- bg(x, bg = "white", part = "footer")
  x <- color(x, color = "black", part = "all")
  x <- padding(x, padding = 1, part = "all")
  x <- border_outer(x, part="all", border = thk_border )
  x <- border_inner_h(x, border = std_border, part="all")
  x <- border_inner_v(x, border = std_border, part="all")
  x <- vline(x, j = c(1,thcols), border = thk_border, part = "all")
  x <- set_table_properties(x, layout = "fixed")
  x
}
df2 |> 
  flextable() |> 
  separate_header() |> 
  autofit() |> theme_design()


#Species_Composition
taxon.fill <- merge(data.frame(group = unique(veg$landuse)), data.frame(taxon = unique(veg$taxon), Low = 0, RV = 0, High = 0)) |> mutate(type = vegnasis::fill.type(taxon)) |> unique() 
taxon.fill <- taxon.fill[,c('group','taxon', 'type', 'Low', 'RV', 'High')]

veg.comp.summary <-  veg  |> summary.ESIS(group='landuse', breaks = c(5), normalize = F,  
                                          lowerQ = 0, upperQ = 1) |> ungroup()
veg.comp.summary <- veg.comp.summary |> mutate(Low = cover.Low, RV=cover.mean, High=cover.High)
overstory <- veg.comp.summary |> subset(Top > 5, select = c("group","taxon", "type","Low","RV","High"))
#add missing rows
o2 <- subset(taxon.fill, taxon %in% overstory$taxon)
o2 <- subset(o2, !paste(taxon,group) %in% paste(overstory$taxon,overstory$group) )
overstory <- overstory |> rbind(o2)


allplots <- overstory |> group_by(taxon, type) |> summarise(group = "All Landuses", Low = min(Low), RV = mean(RV), High = max(High)) |> arrange(-RV )
factorgroup <- unique(overstory$group)
factortaxon <- allplots$taxon
overstory <- rbind(overstory, allplots)
overstory$taxon <- factor(overstory$taxon, levels = factortaxon)
overstory$group <- factor(overstory$group, levels = c(factorgroup,"All Landuses"))
overstory <- overstory |> arrange(group, taxon)

overstory |> 
  knitr::kable(row.names = FALSE, digits = c(1,1,1,1,1)) %>%
  remove_column(1) |> column_spec(1,italic=T) |>
  kableExtra::group_rows(index = table(overstory$group)) |>
  kable_classic(full_width = F, html_font = "Cambria")


#Flextable ---- 

overstory.wide <- overstory  |> mutate(Low = condRound1(Low), RV = condRound1(RV), High = condRound1(High)) |> tidyr::pivot_wider(names_from = group, values_from = c(Low,RV,High)) |> as.data.frame()

ngroups <- length(unique(overstory$group))
pcolors <- palette.colors(ngroups+1, palette = "ggplot2")
pcolors <- pcolors[2:length(pcolors)]
pcolors <- c('white','white',pcolors,pcolors,pcolors)
thcols <- 1:ngroups
thcols <- 3*thcols+2
df2 <- overstory.wide

repnames <- colnames(df2)
repnames <- stringr::str_split_fixed(repnames, '_', 2)
repnamesA <- repnames[,2]
repnamesB <- repnames[,1]
repdf <- data.frame(A=repnamesA, B=repnamesB, C=pcolors)
repdf <- repdf |> mutate(seq = 1:nrow(repdf), 
                         seq2 = c(1:2,(1:ngroups)+2,(1:ngroups)+2,(1:ngroups)+2))
repdf <- repdf |> arrange(seq2)
repnames <- paste0(repnames[,2],'_',repnames[,1])
colnames(df2) <- repnames 
df2 <- df2[,repdf$seq]
colnames(df2)[1:2]<- c('Taxon','Habit')

theme_design <- function(x) {
  x <- border_remove(x)
  std_border <- fp_border_default(width = 0.5, color = "black")
  thk_border <- fp_border_default(width = 2, color = "black")
  x <- fontsize(x, size = 10, part = "all")
  x <- font(x, fontname = "Cambria", part = "all")
  x <- italic(x, j=1, part = "body")
  x <- align(x, align = "center", part = "all")
  x <- align(x, align = "center", part = "header")
  x <- align(x, align = "left", part = "body", j=1)
  x <- align(x, align = "center", part = "body", j=2)
  x <- bold(x, bold = TRUE, part = "all")
  x <- bg(x, bg = "white", part = "body")
  x <- bg(x, bg = repdf$C, part = "header")
  x <- bg(x, bg = "white", part = "footer")
  x <- color(x, color = "black", part = "all")
  x <- padding(x, padding = 1, part = "all")
  x <- border_outer(x, part="all", border = thk_border )
  x <- border_inner_h(x, border = std_border, part="all")
  x <- border_inner_v(x, border = std_border, part="all")
  x <- vline(x, j = c(2,thcols), border = thk_border, part = "all")
  x <- set_table_properties(x, layout = "fixed")
  x
}
df2 |> 
  flextable() |> 
  separate_header() |> 
  autofit() |> theme_design()


#understory ----
understory <- veg.comp.summary |> subset(Top <= 5, select = c("group","taxon", "type", "Low","RV","High")) 
u2 <- subset(taxon.fill, taxon %in% understory$taxon)
u2 <- subset(u2, !paste(taxon,group) %in% paste(understory$taxon,understory$group))
understory <- understory |> rbind(u2)

allplots <- understory |> group_by(taxon, type) |> summarise(group = "All Landuses", Low = min(Low), RV = mean(RV), High = max(High)) |> arrange(-RV )
keeptaxa <- subset(allplots, High >= 10)$taxon
factorgroup <- unique(understory$group)
factortaxon <- allplots$taxon
understory <- rbind(understory, allplots)
understory$taxon <- factor(understory$taxon, levels = factortaxon)
understory$group <- factor(understory$group, levels = c(factorgroup,"All Landuses"))
understory <- understory |> arrange(group, taxon) |> subset(taxon %in% keeptaxa)

options(knitr.kable.NA = '-')
understory |> #mutate(Low = condRound1(Low), RV = condRound1(RV), High = condRound1(High)) |>
  knitr::kable(row.names = FALSE, digits = c(1,1,1,1,1)) %>% 
  remove_column(1) |> column_spec(1,italic=T) |>
  kableExtra::group_rows(index = table(understory$group)) |>
  kable_classic(full_width = F, html_font = "Cambria")



#understory flextable ----
understory.wide <- understory  |> mutate(Low = condRound1(Low), RV = condRound1(RV), High = condRound1(High)) |> tidyr::pivot_wider(names_from = group, values_from = c(Low,RV,High)) |> as.data.frame()

ngroups <- length(unique(understory$group))
pcolors <- palette.colors(ngroups+1, palette = "ggplot2")
pcolors <- pcolors[2:length(pcolors)]
pcolors <- c('white','white',pcolors,pcolors,pcolors)
thcols <- 1:ngroups
thcols <- 3*thcols+2
df2 <- understory.wide

repnames <- colnames(df2)
repnames <- stringr::str_split_fixed(repnames, '_', 2)
repnamesA <- repnames[,2]
repnamesB <- repnames[,1]
repdf <- data.frame(A=repnamesA, B=repnamesB, C=pcolors)
repdf <- repdf |> mutate(seq = 1:nrow(repdf), 
                         seq2 = c(1:2,(1:ngroups)+2,(1:ngroups)+2,(1:ngroups)+2))
repdf <- repdf |> arrange(seq2)
repnames <- paste0(repnames[,2],'_',repnames[,1])
colnames(df2) <- repnames 
df2 <- df2[,repdf$seq]
colnames(df2)[1:2]<- c('Taxon','Habit')

theme_design <- function(x) {
  x <- border_remove(x)
  std_border <- fp_border_default(width = 0.5, color = "black")
  thk_border <- fp_border_default(width = 2, color = "black")
  x <- fontsize(x, size = 10, part = "all")
  x <- font(x, fontname = "Cambria", part = "all")
  x <- italic(x, j=1, part = "body")
  x <- align(x, align = "center", part = "all")
  x <- align(x, align = "center", part = "header")
  x <- align(x, align = "left", part = "body", j=1)
  x <- align(x, align = "center", part = "body", j=2)
  x <- bold(x, bold = TRUE, part = "all")
  x <- bg(x, bg = "white", part = "body")
  x <- bg(x, bg = repdf$C, part = "header")
  x <- bg(x, bg = "white", part = "footer")
  x <- color(x, color = "black", part = "all")
  x <- padding(x, padding = 1, part = "all")
  x <- border_outer(x, part="all", border = thk_border )
  x <- border_inner_h(x, border = std_border, part="all")
  x <- border_inner_v(x, border = std_border, part="all")
  x <- vline(x, j = c(2,thcols), border = thk_border, part = "all")
  x <- set_table_properties(x, layout = "fixed")
  x
}
df2 |> 
  flextable() |> 
  separate_header() |> 
  autofit() |> theme_design()

```

### Ground Surface Cover

```{r warning=FALSE, message = FALSE, eval=TRUE}
library(ggplot2)
#Transect
#narrow to a project (user site association id)

thesesites <- subset(siteass, usiteassocid %in% 'DSP-F094AB019MI-2024')
gsite <- subset(sites,  usiteid %in% thesesites$usiteid, select=c(siteiid, site_id, commphasename))|> unique()

gsurf <- vegground |> subset(!is.na(groundsurfcovtype) & siteiid %in% gsite$siteiid) |> left_join(gsite,relationship = "many-to-many") |>  mutate(cover = round(ifelse(!is.na(totalpointssampledcount) & !is.na(groundcoverptcount), groundcoverptcount/totalpointssampledcount*100, groundcoverptpct), 1))

gsurf <- gsurf |> mutate(gt = groundsurfcovtype,
                         gtype = case_when(gt %in% c("litter","embedded litter") ~ 'Litter',
                                           gt %in% c("downed wood, coarse-large","downed wood, coarse-small") ~ 'Logs',
                                           gt %in% c("downed wood, fine-large","downed wood, fine-medium","downed wood, fine-small") ~ 'Sticks',
                                           gt %in% c("nonvascular plant") ~ 'Moss',
                                           gt %in% c("forb","tree", "grass or grasslike", "shrub or vine or liana") ~ 'Plant Bases',
                                           gt %in% c("biological crust") ~ 'Lichen',
                                           gt %in% c("bare ground") ~ 'Soil',
                                           gt %in% c("water") ~ 'Water',
                                           gt %in% c("bedrock") ~ 'Bedrock',
                                           gt %in% c("surface fragments, small") ~ 'Gravel',
                                           gt %in% c("surface fragments, large","tree snags, hard","tree snags, soft") ~ 'Rocks'),
                         plot = vegplotid)

gsurf$gtype <- factor(gsurf$gtype, levels = c('Water', 'Bedrock', 'Soil', 'Gravel', 'Rocks', 'Litter', 'Sticks', 'Logs', 'Lichen', 'Moss', 'Plant Bases'))

gcolors <- c('lightcyan', 'gray30', 'lightyellow', 'lightgray', 'darkgray', 'burlywood1', 'burlywood3', 'burlywood4', 'palegreen', 'forestgreen', 'lawngreen')

gsurf2 <- subset(gsurf, !is.na(cover)) |> group_by(vegplotid, commphasename, vegplotname) |> mutate(totalcover = sum(cover)) |>  ungroup() |> group_by(vegplotid, commphasename, vegplotname, gtype)  |>
  # group_by(gtype) |>
  summarise(Cover = sum(cover/totalcover*100))
# pie(x = gsurf2$Cover, labels = gsurf2$gtype, col=gcolors)

ggplot(gsurf2)+
  geom_col(aes(x=vegplotname, y=Cover, fill=gtype))+
  scale_fill_manual(breaks = levels(gsurf2$gtype), values = gcolors)+
  scale_x_discrete(name = 'Plot')+
  scale_y_continuous(expand = c(0,0))

```



### Structural Triangle

```{r warning=FALSE, fig.width=9, fig.height=6, message = FALSE, eval=TRUE}
library(ggtern)
thesesites <- subset(siteass, usiteassocid %in% 'DSP-F094AB019MI-2024')
sites <- subset(sites, usiteid %in% thesesites$usiteid)

landuse <- data.frame(siteobsiid=sites$siteobsiid, landuse = sites$commphasename)
landuse <- landuse |> left_join(data.frame(siteobsiid=vegplot$siteobsiid, plot = vegplot$vegplotid)) |> subset(!is.na(plot) & !is.na(landuse))
veg <- clean.veg(veg.raw)|> subset(!is.na(taxon))
veg <- veg |> inner_join(landuse)

veg <- veg |> mutate(type=NA) |> fill.type.df() |> fill.hts.df()
veg <- veg |> mutate(taxon = harmonize.taxa(veg$taxon, fix = TRUE, sensu = "usda"))

#Get vegetation Structure ----
veg <- veg  |> mutate(tree = ifelse(type %in% c('tree', 'shrub/vine') & ht.max > 5,cover,0),
                      woody = ifelse(type %in% c('tree', 'shrub/vine'),cover,0))

veg.tern <- veg |> group_by(plot, label) |> summarise(tree = cover.agg(tree), woody = cover.agg(woody), shrub = woody - tree, open = 100 - woody)
veg.tern <- veg.tern |> left_join(landuse)

s1 <- data.frame(open = c(35,0,0),
                 tree = c(65,100,65),
                 shrub = c(0,0,35), group="1 forest")

s2 <- data.frame(open = c(25,25,0,0),
                 tree = c(10,65,65,10),
                 shrub = c(65,10,35,90), group="2 dense scrubby woodland")

s3 <- data.frame(open = c(80,25,25),
                 tree = c(10,65,10),
                 shrub = c(10,10,65), group="3 open scrubby woodland")

s4 <- data.frame(open = c(90,35,25,80),
                 tree = c(10,65,65,10),
                 shrub = c(0,0,10,10), group="4 open woodland/savanna")

s5 <- data.frame(open = c(25,25,0,0),
                 tree = c(0,10,10,0),
                 shrub = c(75,65,90,100), group="5 shrub thicket")

s6 <- data.frame(open = c(90,80,25,25),
                 tree = c(0,10,10,0),
                 shrub = c(10,10,65,75), group="6 open shrubland")

s7 <- data.frame(open = c(100,90,80,90),
                 tree = c(0,10,10,0),
                 shrub = c(0,0,10,10), group="7 open grassland")

str.polys = rbind(s1,s2,s3,s4,s5,s6,s7)

gp <- ggtern() +
  geom_polygon(data=str.polys, aes(fill=group, x=open, y=tree, z=shrub),alpha=0.25, linewidth=0.1, color='black') +
  geom_point(data=veg.tern, aes(x=open, y=tree, z=shrub, shape = landuse), size=3)+
  geom_text(data=veg.tern, aes(x=open, y=tree, z=shrub, label=label), vjust=-1, hjust=1, size=2)+

  scale_shape_manual(values=c(17, 16, 8)) +
  scale_fill_manual(values=c('darkcyan','darkgreen','green','yellowgreen','red','orange','yellow')) +
  theme(legend.position=c(0,1),legend.justification=c(0,1)) +theme_nomask()+
  labs(fill="Vegetation Structure")

gp

```

### Structural Profile

```{r warning=FALSE, message = FALSE, eval=TRUE}
#Create slices through the crowns
veg.str <- summary.crown.thickness(veg, breaks = c(c(-1:9)/10,c(2:100)/2)) |> structure.fill.zero() |> subset(type %in% c('tree', 'shrub/vine', 'grass/grasslike',  'forb'))
veg.str <- veg.str |> left_join(landuse)
veg.str.pct <- veg.str |> group_by(landuse, type, stratum, stratum.label, bottom, top) |>
  summarise(X25 = quantile(Cover, 0.05),
            X50 = quantile(Cover, 0.5),
            X75 = quantile(Cover, 0.95))

ggplot(veg.str.pct, aes(x = top, y = X50, col=type)) +
  # plot median
  geom_line() +
  # plot quantiles
  geom_ribbon(aes(ymin = X25, ymax = X75, x = top, fill=type), alpha = 0.2) +
  coord_flip() +
  theme(legend.position = "left")+
  scale_fill_manual(name='Plant Habit', values = c('red', 'orange', 'darkgreen', 'blue'))+
  scale_color_manual(name='Plant Habit', values = c('red', 'orange', 'darkgreen', 'blue'))+
  scale_x_continuous(name='height (m)', breaks=c(0,0.1,0.5,c(1:4),c(1:100)*5),  minor_breaks = NULL, limits = c(0,25), expand = c(0,0), trans = 'sqrt')+
  scale_y_continuous(name='cover', breaks=c((0:5)*20), limits = c(0,100))+
  facet_wrap(~ landuse, nrow=1)

```
